### ISSUE TITLE
Compilation issue on debian jessie and application crash

### ISSUE THREAD

**Issue by mawilmsen** [julznc/dtlsproxy#1]
Hi, I get a compile error when trying to compile on debian jessie:

```
foo@bar:~/dtlsproxy# make
cc -I. -I./tinydtls  -Wall -O2 -g   -c -o main.o main.c
cc -I. -I./tinydtls  -Wall -O2 -g   -c -o utils.o utils.c
cc -I. -I./tinydtls  -Wall -O2 -g   -c -o proxy.o proxy.c
proxy.c: In function 'get_psk_info':
proxy.c:23:9: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
         for (keystore_t *psk=ctx->psk; psk && psk->id; psk=psk->next) {
         ^
proxy.c:23:9: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
<builtin>: recipe for target 'proxy.o' failed
make: *** [proxy.o] Error 1
```

When adding -std=C99 to the Makefile CFLAGS, I get even more errors. However when switching back and forth, I eventually get it compiled since each call compiles some files successfully. 

After compilation however, it crashes with a segfault:

```
foo@bar:~/dtlsproxy# ./dtlsproxy -l 0.0.0.0:5684 -b 127.0.0.1:15683 -k Client_identity:secretPSK
main.c[42] ./dtlsproxy started
proxy.c[159] listen: 0.0.0.0:5684
Segmentation fault
```

Not sure if it has something do do with the "odd" compilation procedure.

I am using debian 8.10, uname -ar shows `Linux bar 4.9.49-moby #1 SMP Fri Dec 8 13:40:02 UTC 2017 x86_64 GNU/Linux`

Any help is appreciated.

**Comment by julznc** [comment]
hi mawilmsen,
for that compile error, please try:
```
keystore_t *psk=NULL;
// ...
for (psk=ctx->psk; psk && psk->id; psk=psk->next) {
// ...
}
```

**Comment by mawilmsen** [comment]
That did the trick and resolved the segfault, thanks.
