### ISSUE TITLE
Dynamically changing PSK

### ISSUE THREAD

**Issue by GrimbiXcode** [julznc/dtlsproxy#2]
Would it be possible to read the PSKs and IDs from a source that could be changed from another program?
For example, you could constantly create new keys from a NodeJS CoAP server for new CoAP clients (or client groups).

Perhaps, there is a need for an additional lock-file to prevent missing config parts while reading.

**Comment by julznc** [comment]
Hi,
Sorry, that's not covered by this project, hence not an "issue".
You can try modifying the "get_psk_info()" in "proxy.c" to have support for that "feature".
Thanks!

**Comment by mateusz-** [comment]
This would be a nice feature.

Another similar project, stunnel (for TLS proxying), uses a config file. The config itself can be reloaded by signaling SIGHUP to the daemon. This, I believe, is a common practice.
